version: '2'

services:
    node:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: wmde/wikibase-vuejs-components 
        volumes:
            - '~/.npm:/.npm'
            - './:/app'
        working_dir: /app
        environment:
            - NODE_DEBUG
