const langs = {
	languages: [
		{ code: 'ar', name: 'العربية' },
		{ code: 'ast', name: 'Asturianu' },
		{ code: 'az', name: 'Azərbaycanca' },
		{ code: 'bg', name: 'Български' },
		{ code: 'nan', name: 'Bân-lâm-gú / Hō-ló-oē' },
		{ code: 'be', name: 'Беларуская' },
		{ code: 'ca', name: 'Català' },
		{ code: 'cs', name: 'Čeština' },
		{ code: 'da', name: 'Dansk' },
		{ code: 'de', name: 'Deutsch' },
		{ code: 'et', name: 'Eesti' },
		{ code: 'el', name: 'Ελληνικά' },
		{ code: 'en', name: 'English' },
		{ code: 'es', name: 'Español' },
		{ code: 'eo', name: 'Esperanto' },
		{ code: 'eu', name: 'Euskara' },
		{ code: 'fa', name: 'فارسی' },
		{ code: 'fr', name: 'Français' },
		{ code: 'gl', name: 'Galego' },
		{ code: 'hy', name: 'Հայերեն' },
		{ code: 'hi', name: 'हिन्दी' },
		{ code: 'hr', name: 'Hrvatski' },
		{ code: 'id', name: 'Bahasa Indonesia' },
		{ code: 'it', name: 'Italiano' },
		{ code: 'he', name: 'עברית' },
		{ code: 'ka', name: 'ქართული' },
		{ code: 'la', name: 'Latina' },
		{ code: 'lv', name: 'Latviešu' },
		{ code: 'lt', name: 'Lietuvių' },
		{ code: 'hu', name: 'Magyar' },
		{ code: 'mk', name: 'Македонски' },
		{ code: 'arz', name: 'مصرى' },
		{ code: 'ms', name: 'Bahasa Melayu' },
		{ code: 'min', name: 'Bahaso Minangkabau' },
		{ code: 'nl', name: 'Nederlands' },
		{ code: 'ja', name: '日本語' },
		{ code: 'nb', name: 'Norsk (bokmål)' },
		{ code: 'nn', name: 'Norsk (nynorsk)' },
		{ code: 'ce', name: 'Нохчийн' },
		{ code: 'uz', name: 'Oʻzbekcha / Ўзбекча' },
		{ code: 'pl', name: 'Polski' },
		{ code: 'pt', name: 'Português' },
		{ code: 'kk', name: 'Қазақша / Qazaqşa / قازاقشا' },
		{ code: 'ro', name: 'Română' },
		{ code: 'ru', name: 'Русский' },
		{ code: 'cy', name: 'Cymraeg' },
		{ code: 'ceb', name: 'Sinugboanong Binisaya' },
		{ code: 'sk', name: 'Slovenčina' },
		{ code: 'sl', name: 'Slovenščina' },
		{ code: 'sr', name: 'Српски / Srpski' },
		{ code: 'sh', name: 'Srpskohrvatski / Српскохрватски' },
		{ code: 'fi', name: 'Suomi' },
		{ code: 'sv', name: 'Svenska' },
		{ code: 'ta', name: 'தமிழ்' },
		{ code: 'th', name: 'ภาษาไทย' },
		{ code: 'tg', name: 'Тоҷикӣ' },
		{ code: 'azb', name: 'تۆرکجه' },
		{ code: 'tr', name: 'Türkçe' },
		{ code: 'uk', name: 'Українська' },
		{ code: 'ur', name: 'اردو' },
		{ code: 'vi', name: 'Tiếng Việt' },
		{ code: 'vo', name: 'Volapük' },
		{ code: 'war', name: 'Winaray' },
		{ code: 'zh', name: '中文' },
		{ code: 'ko', name: '한국어' },
	],
};

export default langs;
